// Generated by scripts/content-index.mjs — do not edit by hand.
import type { LearningObject } from "../schema";
import { MATH } from "./math";
import { MATH_PLUS } from "./math_plus";
import { PHYSICS } from "./physics";
import { PHYSICS_PLUS } from "./physics_plus";
import { CHEMISTRY } from "./chemistry";
import { CHEMISTRY_PLUS } from "./chemistry_plus";
import { BIOLOGY } from "./biology";
import { BIOLOGY_PLUS } from "./biology_plus";
import { NEURO } from "./neuroscience";
import { PROGRAMMING } from "./programming";
import { PROGRAMMING_PLUS } from "./programming_plus";
import { RESEARCH } from "./research";
import { COMPETITION } from "./competition";
import { EARTH } from "./earth";
import { ENVIRONMENT } from "./environment";
import { PSYCHOLOGY } from "./psychology";
import { ECONOMICS } from "./economics";
import { CULTURE } from "./culture";
import { CULTURE_PLUS } from "./culture_plus";
import { WRITING } from "./writing";
import { ARTS } from "./arts";
import { MEDIA } from "./media";
import { ENGLISH, GERMAN, JAPANESE } from "./languages";

/** Canonical (Turkish-authored) content of Lab Curriculum, in display order. */
export const BASE_OBJECTS: LearningObject[] = [
  ...MATH,
  ...MATH_PLUS,
  ...PHYSICS,
  ...PHYSICS_PLUS,
  ...CHEMISTRY,
  ...CHEMISTRY_PLUS,
  ...BIOLOGY,
  ...BIOLOGY_PLUS,
  ...NEURO,
  ...PROGRAMMING,
  ...PROGRAMMING_PLUS,
  ...RESEARCH,
  ...COMPETITION,
  ...EARTH,
  ...ENVIRONMENT,
  ...PSYCHOLOGY,
  ...ECONOMICS,
  ...CULTURE,
  ...CULTURE_PLUS,
  ...WRITING,
  ...ARTS,
  ...MEDIA,
  ...ENGLISH,
  ...GERMAN,
  ...JAPANESE,
];
