import type { CurriculumSpec } from "../../engines/curriculumSpec";
import { expr, mc, num, open } from "./helpers";

/** Elle yazılmış paket: olimpiyat odaklı giriş mekaniği. */
export const mechanicsPack: CurriculumSpec = {
  title: "Mekanik — Fizik Olimpiyatı Hattı",
  subject: "Fizik",
  goal: "Daha önce görmediğin mekanik sistemleri modelleyip olimpiyat düzeyindeki mekanik problemlerini temel ilkelerden çözebilmek.",
  description: "Vektörler → kinematik → Newton yasaları; ardından enerji ve momentum dallarına ayrılır, karma olimpiyat problemleriyle biter.",
  units: [
    {
      title: "Matematiksel araçlar",
      summary: "Mekaniğin dili: vektörler ve değişim hızları.",
      topics: [
        {
          title: "Vektörler",
          concepts: [{ key: "vec", title: "Vektör bileşenleri", description: "Bir vektör, seçilen eksenler boyunca bileşenleriyle tanımlanır." }],
          milestones: [
            {
              key: "vec1", type: "CONCEPT", difficulty: 1, estimatedMinutes: 8, conceptKeys: ["vec"],
              title: "Bir vektörü bileşenlerine ayır",
              learningObjective: "Büyüklüğü ve yönü verilen bir vektörün x ve y bileşenlerini hesapla ve işaretlerini kontrol et.",
              masteryCriterion: "Tam çözüme bakmadan iki bileşen hesabını doğru yap.",
              tags: ["vektörler", "trigonometri"],
              questions: [
                num("MASTERY", "10 N'luk bir kuvvet +x ekseninin 30° üstünü gösteriyor. x-bileşeni nedir?", 8.66, "N",
                  ["Vektörü çiz ve x eksenine bir dikme indir.", "x-bileşeni 30° açısına komşu kenardır.", "Komşu kenar = hipotenüs × cos(açı).", "Fx = 10 · cos 30°."], "Fx = 10 cos 30° = 8,66 N."),
                num("MASTERY", "25 m/s'lik bir hız +x ekseninin 53° altını gösteriyor. y-bileşeni nedir (işaretiyle)?", -19.97, "m/s",
                  ["x ekseninin \"altı\" hangi yön?", "y-bileşeni açının karşısındaki kenardır.", "Karşı kenar için sinüs kullan, sonra işareti belirle.", "vy = −25 · sin 53°."], "vy = −25 sin 53° ≈ −19,97 m/s."),
                num("RETENTION", "12 N'luk bir kuvvet +x ekseninin 60° üstünü gösteriyor. y-bileşeni nedir?", 10.39, "N",
                  ["Çiz.", "Açının karşısındaki kenar.", "sin kullan.", "12 · sin 60°."], "Fy = 12 sin 60° = 10,39 N."),
                num("TRANSFER", "Bir kutu 20° eğimli bir rampanın üzerinde duruyor. Ağırlığı 50 N. Ağırlığın rampa boyunca bileşeni nedir?", 17.1, "N",
                  ["Eksenleri rampaya paralel ve dik seç.", "Ağırlık ile dik eksen arasındaki açı eğim açısına eşittir.", "Rampa boyunca bileşen eğim açısının sinüsünü kullanır.", "50 · sin 20°."], "W∥ = 50 sin 20° ≈ 17,1 N."),
              ],
            },
            {
              key: "vec2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 12, prerequisites: ["vec1"],
              title: "Vektörleri bileşenleriyle topla",
              learningObjective: "İki veya daha fazla vektörü bileşenlerini toplayarak topla ve bileşkenin büyüklüğünü ve yönünü bul.",
              tags: ["vektörler"],
              questions: [
                num("MASTERY", "A = (3, 4) ve B = (1, −1). |A + B| nedir?", 5, undefined,
                  ["Aynı bileşenleri topla.", "A + B = (3+1, 4−1).", "Büyüklük √(x² + y²).", "√(4² + 3²)."], "A + B = (4, 3), |A + B| = 5."),
                num("MASTERY", "Bir yürüyüşçü 4 km doğuya, sonra 3 km kuzeye, sonra 1 km batıya yürüyor. Başlangıçtan uzaklığı kaç km?", 4.24, "km",
                  ["Her bacağı bir vektör olarak yaz.", "Doğu +x, kuzey +y.", "Toplam: (4 − 1, 3).", "√(3² + 3²)."], "Yer değiştirme (3, 3) km → 3√2 ≈ 4,24 km."),
                num("RETENTION", "A = (−2, 5), B = (6, −2). |A + B| nedir?", 5, undefined,
                  ["Bileşenleri topla.", "(4, 3).", "Pisagor.", "5."], "(4, 3) → 5."),
                num("TRANSFER", "Bir halkaya iki kuvvet etki ediyor: +x yönünde 30 N ve +y yönünde 40 N. Halkayı dengede tutacak tek kuvvetin büyüklüğü (N) nedir?", 50, "N",
                  ["Denge, toplam kuvvetin sıfır olması demektir.", "Önce iki kuvvetin bileşkesini bul.", "Dengeleyici kuvvet bileşkeyle aynı büyüklüktedir.", "√(30² + 40²)."], "Bileşke 50 N; ters yönde 50 N'luk bir kuvvet gerekir."),
              ],
            },
          ],
        },
        {
          title: "Değişim hızları",
          milestones: [
            {
              key: "calc1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 12, optional: true, prerequisites: [],
              title: "Konumun türevinden hızı bul",
              learningObjective: "Polinom bir x(t) fonksiyonundan v(t) ve a(t)'yi elde et ve her türevin fiziksel anlamını yorumla.",
              tags: ["türev"],
              questions: [
                expr("MASTERY", "x(t) = 3t² + 2t − 5. v(t)'yi yaz.", ["6*t + 2"], ["t"],
                  ["Hız, konumun değişim hızıdır.", "Terim terim türev al.", "d/dt(tⁿ) = n·tⁿ⁻¹; sabitler kaybolur.", "d/dt(3t²) = 6t, d/dt(2t) = 2."], "v(t) = 6t + 2."),
                expr("MASTERY", "x(t) = t³ − 4t. a(t)'yi yaz.", ["6*t"], ["t"],
                  ["İvme ikinci türevdir.", "Önce v(t) = 3t² − 4 bul.", "Tekrar türev al.", "a(t) = 6t."], "v = 3t² − 4, a = 6t."),
                expr("RETENTION", "x(t) = 5t² − t. v(t)'yi yaz.", ["10*t - 1"], ["t"],
                  ["Türev al.", "Kuvvet kuralı.", "10t …", "10t − 1."], "v = 10t − 1."),
                num("TRANSFER", "x(t) = 2t³ − 9t² + 12t (m). Parçacık t > 1,5 s iken hangi anda bir an durur?", 2, "s",
                  ["Durmak v = 0 demektir.", "v(t) = 6t² − 18t + 12.", "6'ya böl: t² − 3t + 2 = 0.", "Kökler t = 1 ve t = 2."], "v = 6(t − 1)(t − 2) → t = 2 s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Kinematik",
      summary: "Hareketi nedenini sormadan betimlemek.",
      topics: [
        {
          title: "Hareket grafikleri ve sabit ivme",
          milestones: [
            {
              key: "kin1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 10, prerequisites: ["vec2"],
              title: "Konum–zaman grafiğinden hızı oku",
              learningObjective: "x(t) eğiminden hızın nerede sıfır, pozitif ya da negatif olduğunu belirle.",
              interaction: "GRAPH_INTERPRETATION",
              tags: ["grafikler"],
              questions: [
                { kind: "GRAPH_INTERPRETATION", purpose: "MASTERY", prompt: "Grafik x(t) = t² − 4t (m) fonksiyonunu gösteriyor. Hız hangi anda sıfırdır?",
                  graph: { expression: "x^2 - 4*x", xMin: 0, xMax: 5, xLabel: "t (s)", yLabel: "x (m)" }, numeric: { value: 2, tolerance: 0.03, unit: "s" },
                  hints: ["Hız, x(t)'nin eğimidir.", "Teğet nerede yatay?", "Parabolün dönüm noktası.", "t² − 4t'nin tepe noktası t = 2'de."], solution: "Eğim tepe noktasında sıfırdır: t = 2 s." },
                { kind: "GRAPH_INTERPRETATION", purpose: "MASTERY", prompt: "Aynı x(t) = t² − 4t için cisim hangi aralıkta −x yönünde hareket eder?",
                  graph: { expression: "x^2 - 4*x", xMin: 0, xMax: 5, xLabel: "t (s)", yLabel: "x (m)" },
                  choices: ["0 < t < 2", "2 < t < 4", "0 < t < 4", "t > 4"], correctChoice: 0,
                  hints: ["Negatif hız = negatif eğim.", "Eğri nerede aşağı iniyor?", "Tepe noktasından önce eğri azalıyor.", "0 < t < 2."], solution: "Eğim tepe noktasından önce negatiftir: 0 < t < 2." },
                { kind: "GRAPH_INTERPRETATION", purpose: "RETENTION", prompt: "x(t) = 6t − t² (m). Cisim hangi anda geri döner?",
                  graph: { expression: "6*x - x^2", xMin: 0, xMax: 6, xLabel: "t (s)", yLabel: "x (m)" }, numeric: { value: 3, tolerance: 0.03, unit: "s" },
                  hints: ["Geri dönmek v = 0 demektir.", "Yatay teğet.", "Parabolün tepe noktası.", "t = 3."], solution: "t = 3 s." },
                mc("TRANSFER", "Bir top düşey olarak yukarı atılıyor. Hız–zaman grafiği için hangisi doğrudur?",
                  ["Negatif eğimli, tepe noktasında sıfırı kesen bir doğrudur", "Tepe noktası en yüksek noktada olan bir paraboldür", "Tepeye kadar sabittir, sonra aniden negatife atlar", "İvme sabit olduğu için her yerde sıfırdır"], 0,
                  ["Uçuş sırasında ivme nedir?", "Sabit ivme ⇒ v(t) doğrusaldır.", "Eğim −g'dir.", "v en yüksek noktada sıfırı keser."], "Sabit ivme −g, en yüksek noktada v = 0'dan geçen bir doğru verir."),
              ],
            },
            {
              key: "kin2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 15, prerequisites: ["kin1"],
              title: "Sabit ivmeli hareket problemlerini çöz",
              learningObjective: "Bilinen ve bilinmeyen büyüklüklere göre doğru kinematik bağıntıyı seç ve çöz.",
              tags: ["sabit ivme"],
              questions: [
                num("MASTERY", "Bir araba durgun hâlden a = 3 m/s² ile hızlanıyor. 4 s'de ne kadar yol alır?", 24, "m",
                  ["Bilinenleri listele: v₀, a, t.", "Son hızı bilmeden yer değiştirme lazım.", "x = v₀t + ½at².", "½ · 3 · 4²."], "x = ½·3·16 = 24 m."),
                num("MASTERY", "12 m/s hızla giden bir bisikletli düzgün yavaşlayarak 18 m'de duruyor. Yavaşlamanın büyüklüğü nedir?", 4, "m/s²",
                  ["Zaman verilmemiş.", "t içermeyen bağıntıyı kullan.", "v² = v₀² + 2aΔx.", "0 = 144 + 2a·18."], "a = −144/36 = −4 m/s²."),
                num("MASTERY", "Bir taş durgun hâlden bırakılıyor. 20 m düştükten sonra hızı nedir? (g = 9,8 m/s²)", 19.8, "m/s",
                  ["Serbest düşmede a = g.", "Zaman verilmemiş.", "v² = 2gh.", "√(2·9,8·20)."], "v = √392 ≈ 19,8 m/s."),
                num("RETENTION", "Durgun hâlden, 5 s boyunca a = 2 m/s². Son hız?", 10, "m/s",
                  ["v = v₀ + at.", "v₀ = 0.", "2·5.", "10."], "v = 10 m/s."),
                num("TRANSFER", "Bir tren bir sinyalin önünden 20 m/s ile geçiyor ve 0,5 m/s² ile yavaşlıyor. Sinyalden 300 m ilerlemesi kaç saniye sürer?", 20, "s",
                  ["x(t)'yi yaz ve 300'e eşitle.", "300 = 20t − 0,25t².", "İkinci dereceden denklemi çöz; ilk zamanı seç.", "t² − 80t + 1200 = 0 → t = 20 veya 60."], "t = 20 s (60 s kökü, tren durduktan sonraya denk gelir)."),
              ],
            },
          ],
        },
        {
          title: "İki boyutlu hareket",
          milestones: [
            {
              key: "kin3", type: "APPLICATION", difficulty: 3, estimatedMinutes: 25, prerequisites: ["kin2", "vec2"],
              title: "Eğik atış hareketini analiz et",
              learningObjective: "Yatay ve düşey hareketi bağımsız ele alarak uçuş süresini, menzili ve maksimum yüksekliği bul.",
              interaction: "SIMULATION",
              tags: ["eğik atış"],
              questions: [
                { kind: "SIMULATION", purpose: "PRACTICE", prompt: "Simülatörü kullan: menzil R = v²·sin(2θ)/g. Her hız için menzili en büyük yapan atış açısını (derece) bul.",
                  simulation: { expression: "v^2*sin(2*th*pi/180)/9.8", outputLabel: "Menzil R (m)", variables: [
                    { name: "v", label: "Hız v (m/s)", min: 5, max: 30, step: 1, initial: 15 },
                    { name: "th", label: "Açı θ (°)", min: 5, max: 85, step: 1, initial: 30 }] },
                  numeric: { value: 45, tolerance: 0.02, unit: "°" },
                  hints: ["v'yi sabit tutup θ'yı değiştir.", "R'nin artmayı bıraktığı yere bak.", "sin(2θ), 2θ = 90° iken en büyüktür.", "θ = 45°."], solution: "sin 2θ en büyük değerini 2θ = 90°'de alır, yani θ = 45°." },
                num("MASTERY", "Bir top düz zeminden 20 m/s hızla, yatayla 45° açıyla atılıyor. Menzili nedir? (g = 9,8)", 40.8, "m",
                  ["v'yi bileşenlerine ayır.", "Uçuş süresi T = 2v sinθ / g.", "R = vₓ · T = v² sin 2θ / g.", "400 · 1 / 9,8."], "R = 400/9,8 ≈ 40,8 m."),
                num("MASTERY", "Bir top 1,8 m yüksekliğindeki masadan yatay olarak 8 m/s hızla fırlatılıyor. Masadan ne kadar uzağa düşer? (g = 9,8)", 4.85, "m",
                  ["Düşey hareket sıfır düşey hızla başlar.", "1,8 = ½gt²'den zaman.", "t ≈ 0,606 s.", "x = 8 · t."], "t = √(3,6/9,8) ≈ 0,606 s, x ≈ 4,85 m."),
                num("RETENTION", "Yatayla 30° açıyla 15 m/s hızla atılıyor. Maksimum yükseklik? (g = 9,8)", 2.87, "m",
                  ["Sadece düşey hareket önemli.", "v_y = 15 sin 30° = 7,5.", "h = v_y² / 2g.", "56,25/19,6."], "h ≈ 2,87 m."),
                num("TRANSFER", "500 m yükseklikte 60 m/s ile yatay uçan bir uçaktan bir paket bırakılıyor. Paket bırakıldığı noktanın ne kadar ilerisine düşer? (g = 9,8)", 606, "m",
                  ["Paket uçağın yatay hızını korur.", "500 = ½gt²'den düşme süresi.", "t ≈ 10,1 s.", "x = 60 · 10,1."], "t = √(1000/9,8) ≈ 10,10 s → x ≈ 606 m."),
              ],
            },
            {
              key: "kin4", type: "DERIVATION", difficulty: 4, estimatedMinutes: 30, optional: true, prerequisites: ["kin3"],
              title: "Yörünge denklemi y(x)'i türet",
              learningObjective: "Eğik atış denklemlerinden zamanı yok ederek y(x) yolunu elde et ve bunun bir parabol olduğunu göster.",
              tags: ["türetme", "eğik atış"],
              questions: [
                expr("MASTERY", "Orijinden v hızı ve th açısıyla atış, yerçekimi g. y'yi x'in fonksiyonu olarak yaz (x, v, th, g değişkenleri).",
                  ["x*tan(th) - g*x^2/(2*v^2*cos(th)^2)"], ["x", "v", "th", "g"],
                  ["x(t) ve y(t)'yi ayrı yaz.", "x = v cos(th) t, yani t = x / (v cos th).", "t'yi y = v sin(th) t − ½ g t² içine koy.", "y = x tan th − g x² / (2 v² cos² th)."], "y = x·tan θ − g x² / (2v² cos² θ)."),
                open("DERIVATION", "MASTERY", "Yörüngenin neden parabol olduğunu adım adım açıkla. Zamanı yok eden adımı belirt.",
                  ["x, t'ye göre doğrusaldır", "x(t)'den t çözülür", "y(t) içine yerleştirilir", "y, x'e göre ikinci derecedendir"],
                  ["Bileşen denklemlerinden başla.", "Hangi denklemi tersine çevirmek en kolay?", "x(t), t'ye göre doğrusal.", "Yerine koyunca y'de yalnızca x ve x² kalır."], "x = v cosθ t doğrusal olduğundan t = x/(v cosθ); bunu y(t)'ye koyunca x'e göre ikinci dereceden bir ifade, yani parabol elde edilir."),
                expr("TRANSFER", "y(x)'i kullanarak düz zeminde menzil R'yi v, th, g cinsinden yaz (y = 0, x ≠ 0).",
                  ["v^2*sin(2*th)/g", "2*v^2*sin(th)*cos(th)/g"], ["v", "th", "g"],
                  ["y = 0 al ve x'e böl.", "tan th = g R / (2 v² cos² th).", "R = 2 v² sin th cos th / g.", "İki kat açı özdeşliğini kullan."], "R = v² sin 2θ / g."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Newton yasaları",
      summary: "Hareket neden değişir: kuvvetler ve etkileri.",
      topics: [
        {
          title: "Kuvvetler ve serbest cisim diyagramları",
          concepts: [{ key: "fbd", title: "Serbest cisim diyagramı", description: "Yalıtılmış tek bir cisme etki eden tüm dış kuvvetler." }],
          milestones: [
            {
              key: "n1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 15, prerequisites: ["vec2"], conceptKeys: ["fbd"],
              title: "Serbest cisim diyagramı çiz",
              learningObjective: "Verilen bir fiziksel durumda seçilen cisme etki eden her kuvveti belirle ve doğru bir serbest cisim diyagramı çiz.",
              interaction: "DIAGRAM",
              masteryCriterion: "Daha önce görülmemiş iki durumda kuvvetlerin doğru kümesini belirle.",
              tags: ["kuvvetler", "SCD"],
              questions: [
                open("DIAGRAM", "PRACTICE", "Pürüzlü bir eğik düzlemden aşağı kayan bir bloğun serbest cisim diyagramını çiz. Her kuvveti etiketle.",
                  ["dikey olarak aşağı yönlü ağırlık mg", "eğik düzleme dik normal kuvvet", "eğik düzlem boyunca yukarı kinetik sürtünme (harekete zıt)", "\"hareket kuvveti\" gibi fazladan kuvvet yok"],
                  ["Bloğu yalıt. Ona ne dokunuyor?", "Temas kuvvetleri: yalnızca yüzey. Alan kuvvetleri: yerçekimi.", "Yüzey iki bileşen verir: dik ve paralel.", "Sürtünme kayma yönüne zıttır."], "Üç kuvvet: ağırlık (aşağı), normal (yüzeye dik), kinetik sürtünme (eğim boyunca yukarı)."),
                mc("MASTERY", "Bir kitap masanın üzerinde duruyor. KİTABA hangi kuvvetler etki eder?",
                  ["Ağırlık ve masanın normal kuvveti", "Ağırlık, normal kuvvet ve kitabın masaya uyguladığı kuvvet", "Yalnızca ağırlık", "Ağırlık, normal kuvvet ve yukarı yönlü hava basıncı kuvveti"], 0,
                  ["Yalnızca kitaba etki eden kuvvetler sayılır.", "Kitabın masaya bastırması masaya etki eder.", "İki etkileşim: Dünya ve masa.", "Ağırlık ve normal."], "Ağırlık (Dünya'nın kitaba) ve normal (masanın kitaba)."),
                { kind: "CLASSIFICATION", purpose: "MASTERY", prompt: "Bir ipe bağlı top düşey bir çemberde dönüyor. Aday kuvvetleri sınıflandır.",
                  classification: { categories: ["Topa etki eder", "Topa etki eden gerçek bir kuvvet değil"], items: [
                    { text: "İpteki gerilme", category: "Topa etki eder" },
                    { text: "Yerçekimi", category: "Topa etki eder" },
                    { text: "Merkezcil kuvvet (ayrı, ek bir kuvvet olarak)", category: "Topa etki eden gerçek bir kuvvet değil" },
                    { text: "Topun hareket kuvveti", category: "Topa etki eden gerçek bir kuvvet değil" }] },
                  hints: ["Topa fiziksel olarak ne dokunuyor?", "Merkezcil, net kuvvetin yönünü anlatır; yeni bir kuvvet değildir.", "Hareketin sürmesi için kuvvet gerekmez.", "Yalnızca gerilme ve yerçekimi."], solution: "Yalnızca gerilme ve yerçekimi etki eder; bunların bileşkesi merkezcil ivmeyi sağlar." },
                mc("RETENTION", "Bir sandık pürüzlü zeminde yatay bir iple sabit hızla çekiliyor. Sandığa kaç kuvvet etki eder?",
                  ["4", "3", "2", "5"], 0,
                  ["Temas ve alan kuvvetlerini listele.", "İp, zemin (iki bileşen), Dünya.", "Gerilme, normal, sürtünme, ağırlık.", "4."], "Ağırlık, normal, sürtünme, gerilme: 4."),
                mc("TRANSFER", "Bir mıknatıs buzdolabının dikey kapısına kaymadan yapışıyor. Ağırlığını ne dengeler?",
                  ["Kapının statik sürtünmesi", "Manyetik kuvvet", "Normal kuvvet", "Hiçbir şey — yavaşça ivmeleniyor"], 0,
                  ["Ağırlık hangi yönde?", "Manyetik ve normal kuvvetler yataydır.", "Düşey bir kuvvet gerekir.", "Yüzeyin sürtünmesi."], "Manyetik çekim ve normal kuvvet yataydır; ağırlığı statik sürtünme dengeler."),
              ],
            },
            {
              key: "n2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 15, prerequisites: ["n1"],
              title: "Newton'un ikinci yasasını tek cisme uygula",
              learningObjective: "Seçilen eksenler boyunca ΣF = ma yaz ve bilinmeyen bir kuvveti ya da ivmeyi çöz.",
              tags: ["Newton 2"],
              questions: [
                num("MASTERY", "5 kg'lık bir kutu 20 N ile itiliyor; kinetik sürtünme 5 N. İvmesi nedir?", 3, "m/s²",
                  ["SCD çiz.", "Net yatay kuvvet = itme − sürtünme.", "a = F_net / m.", "15 / 5."], "a = (20 − 5)/5 = 3 m/s²."),
                num("MASTERY", "70 kg'lık biri 2 m/s² ile yukarı ivmelenen bir asansörde duruyor. Baskül kaç N gösterir? (g = 9,8)", 826, "N",
                  ["Kuvvetler: normal (baskül) yukarı, ağırlık aşağı.", "N − mg = ma.", "N = m(g + a).", "70 · 11,8."], "N = 70 · 11,8 = 826 N."),
                num("RETENTION", "2 kg'lık bir kütleye 9 N net kuvvet etki ediyor. İvme?", 4.5, "m/s²",
                  ["F = ma.", "a = F/m.", "9/2.", "4,5."], "4,5 m/s²."),
                num("TRANSFER", "Sürtünmesiz 30°'lik eğik düzlem. Aşağı kayan bir bloğun ivmesi nedir? (g = 9,8)", 4.9, "m/s²",
                  ["Eksenleri eğik düzlem boyunca seç.", "Yalnızca ağırlığın eğim boyunca bileşeni dengelenmemiştir.", "a = g sin θ.", "9,8 · 0,5."], "a = g sin 30° = 4,9 m/s²."),
              ],
            },
            {
              key: "n3", type: "PRACTICE", difficulty: 3, estimatedMinutes: 20, prerequisites: ["n2"],
              title: "Statik ve kinetik sürtünme üzerine akıl yürüt",
              learningObjective: "Sürtünmenin statik mi kinetik mi olduğuna karar ver ve μN'yi yalnızca geçerli olduğunda kullan.",
              tags: ["sürtünme"],
              questions: [
                num("MASTERY", "Bir eğik düzlemdeki bloğun μs = 0,5. Blok hangi açıda (derece) kaymaya başlar?", 26.57, "°",
                  ["Eşikte statik sürtünme en büyük değerindedir.", "mg sinθ = μs mg cosθ.", "tan θ = μs.", "arctan(0,5)."], "θ = arctan 0,5 ≈ 26,6°."),
                num("MASTERY", "Zemindeki 10 kg'lık bir sandık (μs = 0,4, μk = 0,3) yatay olarak 30 N ile itiliyor. Sürtünme kuvveti kaç N? (g = 9,8)", 30, "N",
                  ["İtme hareketi başlatmaya yetiyor mu?", "En büyük statik sürtünme = μs N = 0,4 · 98 = 39,2 N.", "30 N < 39,2 N, yani hareket etmez.", "Statik sürtünme itmeye eşittir."], "Durgun kalır; statik sürtünme = 30 N (μN değil)."),
                num("RETENTION", "μk = 0,2; 5 kg'lık bir blok düz zeminde kayıyor. Sürtünme kuvveti? (g = 9,8)", 9.8, "N",
                  ["Kinetik sürtünme = μk N.", "N = mg.", "0,2 · 49.", "9,8."], "9,8 N."),
                num("TRANSFER", "Bir araba düz yolda, lastik ile yol arasında μk = 0,7 iken (tekerlekler kilitli) fren yapıyor. 20 m/s'den duruş mesafesi nedir? (g = 9,8)", 29.15, "m",
                  ["Tek yatay kuvvet sürtünme.", "a = μk g.", "v² = 2 a d.", "400 / (2 · 6,86)."], "a = 6,86 m/s², d ≈ 29,2 m."),
              ],
            },
            {
              key: "n4", type: "APPLICATION", difficulty: 3, estimatedMinutes: 25, prerequisites: ["n2"],
              title: "Bağlı cisim sistemlerini çöz",
              learningObjective: "Bağlı bir sistemdeki her cisim için Newton yasasını yaz ve denklem sistemini çöz.",
              tags: ["sistemler", "Atwood"],
              questions: [
                num("MASTERY", "Atwood makinesi: kütlesiz, sürtünmesiz bir makaradan geçen 3 kg ve 5 kg. İvme? (g = 9,8)", 2.45, "m/s²",
                  ["Her kütle için ΣF = ma yaz.", "T − m₁g = m₁a ve m₂g − T = m₂a.", "T'yi yok etmek için topla.", "a = (m₂ − m₁)g/(m₁ + m₂)."], "a = 2·9,8/8 = 2,45 m/s²."),
                expr("MASTERY", "m1 ve m2 kütleli Atwood makinesi için ip gerilmesi T'yi yaz (m1, m2, g değişkenleri).",
                  ["2*m1*m2*g/(m1+m2)"], ["m1", "m2", "g"],
                  ["Önce a'yı bul.", "Sonra T = m1(g + a).", "a = (m2 − m1)g/(m1 + m2) yerine koy.", "Payı sadeleştir."], "T = 2 m₁ m₂ g / (m₁ + m₂)."),
                num("RETENTION", "2 kg ve 6 kg ile Atwood. İvme? (g = 9,8)", 4.9, "m/s²",
                  ["Aynı yöntem.", "a = (m₂ − m₁)g/(m₁ + m₂).", "4·9,8/8.", "4,9."], "4,9 m/s²."),
                num("TRANSFER", "Sürtünmesiz masadaki 4 kg'lık bir blok, kenardaki makaradan asılı 1 kg'lık bir kütleye bağlı. İvme? (g = 9,8)", 1.96, "m/s²",
                  ["İki cisim, tek ip.", "Asılı: mg − T = ma. Masa: T = Ma.", "a = mg/(m + M).", "9,8/5."], "a = 1·9,8/5 = 1,96 m/s²."),
              ],
            },
            {
              key: "n5", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["n2", "kin3"],
              title: "Dairesel harekette merkezcil kuvveti belirle",
              learningObjective: "Net merkeze doğru kuvveti hangi gerçek kuvvetlerin sağladığını belirle ve ΣF = mv²/r uygula.",
              tags: ["dairesel hareket"],
              questions: [
                num("MASTERY", "1000 kg'lık bir araba yarıçapı 50 m olan düz bir virajı 20 m/s ile dönüyor. Gereken sürtünme kuvveti kaç N?", 8000, "N",
                  ["Tek yatay kuvvet sürtünme.", "mv²/r'yi sağlamalı.", "1000 · 400 / 50.", "8000 N."], "f = mv²/r = 8000 N."),
                mc("MASTERY", "Düşey bir çemberin tepesinde bir vagon tam en küçük hızla ilerliyor. Merkezcil kuvveti ne sağlar?",
                  ["Yalnızca yerçekimi", "Yalnızca normal kuvvet", "Yerçekimi artı büyük bir normal kuvvet", "Ayrı bir merkezcil kuvvet"], 0,
                  ["En küçük hızda ray zar zor değer.", "O zaman N → 0.", "mg = mv²/r.", "Yalnızca yerçekimi."], "En küçük hızda N = 0; mv²/r'yi yalnızca yerçekimi sağlar."),
                num("RETENTION", "0,5 m'lik ipe bağlı 0,2 kg'lık bir top yatay çemberde 3 m/s ile dönüyor. Gerilme (yerçekimini ihmal et)?", 3.6, "N",
                  ["T = mv²/r.", "0,2·9/0,5.", "3,6.", "3,6 N."], "3,6 N."),
                num("TRANSFER", "Yarıçapı 2,5 m olan düşey bir çemberin tepesinde en az hangi hız (m/s) gerekir? (g = 9,8)", 4.95, "m/s",
                  ["En küçük hızda normal kuvvet sıfırdır.", "mg = mv²/r.", "v = √(gr).", "√24,5."], "v = √(9,8·2,5) ≈ 4,95 m/s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Enerji",
      summary: "Mekaniğe ikinci bir yol: iş ve korunum.",
      topics: [
        {
          title: "İş ve enerji",
          milestones: [
            {
              key: "e1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 15, prerequisites: ["n2"],
              title: "İş–enerji teoremini kullan",
              learningObjective: "Bir cisme yapılan net işi kinetik enerjisindeki değişimle ilişkilendir.",
              tags: ["enerji"],
              questions: [
                num("MASTERY", "2 kg'lık bir araba 3 m/s'den 5 m/s'ye hızlanıyor. Üzerine yapılan net iş kaç J?", 16, "J",
                  ["W_net = ΔKE.", "KE = ½mv².", "½·2·(25 − 9).", "16 J."], "W = ½·2·(25 − 9) = 16 J."),
                num("MASTERY", "0,5 kg'lık bir disk 4 m/s ile pürüzlü buzda kayarak duruyor. Sürtünmenin yaptığı iş kaç J (işaretiyle)?", -4, "J",
                  ["Sürtünme kinetik enerjiyi alır.", "W = KE_son − KE_ilk.", "0 − ½·0,5·16.", "−4 J."], "W = −4 J."),
                num("RETENTION", "Durgun 4 kg'lık bir cisme 50 J net iş yapılıyor. Son hız?", 5, "m/s",
                  ["50 = ½·4·v².", "v² = 25.", "v = 5.", "5 m/s."], "5 m/s."),
                num("TRANSFER", "25 m/s ile giden 1500 kg'lık bir araba 60 m'de frenleyerek duruyor. Ortalama fren kuvveti kaç N?", 7812.5, "N",
                  ["Fren kuvvetinin işi = ΔKE.", "ΔKE = −½·1500·625.", "F·60 = 468750.", "F = 7812,5 N."], "F = 468750/60 ≈ 7,8 kN."),
              ],
            },
            {
              key: "e2", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["e1"],
              title: "Mekanik enerjinin korunumunu uygula",
              learningObjective: "Mekanik enerjinin ne zaman korunduğunu fark et ve kuvvet ayrıntılarına girmeden hız ve yükseklikleri bul.",
              tags: ["enerji", "korunum"],
              questions: [
                num("MASTERY", "Bir top 5 m'den bırakılıyor. Yere çarpmadan hemen önceki hızı? (g = 9,8)", 9.9, "m/s",
                  ["Potansiyel → kinetik.", "mgh = ½mv².", "v = √(2gh).", "√98."], "v ≈ 9,9 m/s."),
                { kind: "ORDERING", purpose: "MASTERY", prompt: "Enerji korunumu ile çözümün adımlarını sıraya koy.",
                  orderItems: ["Yalnızca korunumlu kuvvetlerin iş yaptığını kontrol et", "Potansiyel enerji için bir sıfır seviyesi seç", "Başlangıçtaki toplam enerjiyi yaz", "Sondaki toplam enerjiyi yaz", "Eşitle ve çöz"],
                  hints: ["Korunumu kullanmadan önce ne doğru olmalı?", "Sonra bir referans gerekir.", "Sonra iki durum.", "En sonda çöz."], solution: "Geçerliliği kontrol et → referans seç → ilk enerji → son enerji → eşitle." },
                num("RETENTION", "Bir sarkaç topu en alt noktasının 0,45 m üstünden bırakılıyor. En alttaki hızı? (g = 9,8)", 2.97, "m/s",
                  ["Enerji korunumu.", "√(2gh).", "√8,82.", "2,97."], "≈ 2,97 m/s."),
                num("TRANSFER", "Bir kayakçı sürtünmesiz 20 m'lik bir tepenin üstünden durgun başlıyor ve 12 m'lik bir tümsekten geçiyor. Tümseğin üstündeki hızı? (g = 9,8)", 12.52, "m/s",
                  ["Yalnızca yükseklik farkı önemli.", "Δh = 8 m.", "v = √(2gΔh).", "√156,8."], "v ≈ 12,5 m/s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Momentum",
      summary: "Üçüncü bir yol: etkileşimler, itme ve çarpışmalar.",
      topics: [
        {
          title: "İtme ve çarpışmalar",
          milestones: [
            {
              key: "p1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 12, prerequisites: ["n2"],
              title: "İtmeyi momentum değişimiyle ilişkilendir",
              learningObjective: "İtmeyi Δp olarak hesapla ve yöne dikkat et.",
              tags: ["momentum"],
              questions: [
                num("MASTERY", "0,5 kg'lık bir top duvara 10 m/s ile çarpıp 8 m/s ile geri sekiyor. İtmenin büyüklüğü (N·s)?", 9, "N·s",
                  ["Momentum bir vektördür.", "Geri sekme yönünü pozitif al.", "Δp = m(8 − (−10)).", "0,5 · 18."], "J = 0,5·18 = 9 N·s."),
                num("MASTERY", "0,15 kg'lık bir topun hızı 0,005 s süren bir vuruşta 0'dan 40 m/s'ye çıkıyor. Ortalama kuvvet (N)?", 1200, "N",
                  ["F_ort = Δp / Δt.", "Δp = 0,15 · 40 = 6.", "6 / 0,005.", "1200 N."], "F = 1200 N."),
                num("RETENTION", "2 kg, aynı yönde 3 m/s'den 7 m/s'ye. İtme?", 8, "N·s",
                  ["Δp = mΔv.", "2·4.", "8.", "8 N·s."], "8 N·s."),
                mc("TRANSFER", "Hava yastıkları bir kazada yaralanmayı neden azaltır?",
                  ["Durma süresini uzatırlar; aynı Δp için ortalama kuvvet küçülür", "Momentum değişimini azaltırlar", "Momentumun tamamını emerler", "Çarpışmayı esnek yaparlar"], 0,
                  ["Hava yastığı Δp'yi değiştirir mi?", "Δp ilk ve son hızlarla belirlenir.", "F = Δp/Δt.", "Daha uzun Δt ⇒ daha küçük F."], "Aynı Δp, daha uzun Δt ⇒ daha küçük ortalama kuvvet."),
              ],
            },
            {
              key: "p2", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["p1"],
              title: "Tek boyutlu çarpışmaları çöz",
              learningObjective: "Momentum korunumunu kullan ve kinetik enerjinin korunup korunmadığına karar ver.",
              tags: ["çarpışmalar"],
              questions: [
                num("MASTERY", "3 m/s ile giden 2 kg'lık bir araba duran 1 kg'lık bir arabaya çarpıp yapışıyor. Son hız?", 2, "m/s",
                  ["Momentum korunur.", "Önceki p = 6 kg·m/s.", "Sonraki toplam kütle = 3 kg.", "6/3."], "v = 2 m/s."),
                num("MASTERY", "Bu çarpışmada kaç J kinetik enerji kaybolur?", 3, "J",
                  ["Önceki ve sonraki KE'yi hesapla.", "Önce: ½·2·9 = 9 J.", "Sonra: ½·3·4 = 6 J.", "9 − 6."], "3 J kaybolur."),
                num("RETENTION", "5 m/s ile giden 4 kg, duran 1 kg'a yapışıyor. Son hız?", 4, "m/s",
                  ["20/5.", "Momentum korunumu.", "Toplam kütle 5.", "4."], "4 m/s."),
                num("TRANSFER", "Durgun 60 kg'lık bir patenci 3 kg'lık bir topu 10 m/s ile ileri atıyor. Patencinin geri tepme hızı?", 0.5, "m/s",
                  ["Toplam momentum sıfır kalır.", "60 v = 3 · 10.", "v = 30/60.", "0,5."], "Geriye doğru 0,5 m/s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Sentez",
      summary: "Yolları birleştiren tekrar, meydan okuma ve final problemleri.",
      topics: [
        {
          title: "Tekrar ve meydan okumalar",
          milestones: [
            {
              key: "rev1", type: "REVIEW", difficulty: 2, estimatedMinutes: 10, prerequisites: ["kin2", "n2"],
              title: "Tekrar: doğru modeli seç",
              learningObjective: "Sorudan hangi ilkenin (kinematik, Newton, enerji) en verimli olduğunu fark et.",
              tags: ["tekrar"],
              questions: [
                mc("MASTERY", "Bir bloğun ilk hızını ve sürtünmesiz rampada çıktığı yüksekliği biliyorsun, son hızı lazım. En verimli yaklaşım?",
                  ["Enerji korunumu", "Rampa boyunca Newton'un ikinci yasası", "Bilinmeyen açıyla kinematik", "Momentum korunumu"], 0,
                  ["Ne bilinmiyor? Ne verilmemiş?", "Zaman ve açı gerekmiyor.", "Yalnızca yükseklikler ve hızlar.", "Enerji."], "Enerji korunumu yalnızca yükseklik ve hızlara ihtiyaç duyar."),
                mc("MASTERY", "İki patenci durgun hâlden birbirini itiyor. Hızlarının oranını bulmak için ne kullanılır?",
                  ["Momentum korunumu", "Enerji korunumu", "Kinematik", "İş–enerji teoremi"], 0,
                  ["Dış yatay kuvvet var mı?", "Yok ⇒ momentum korunur.", "İlk momentum sıfır.", "Momentum."], "Toplam momentum sıfır kalır ⇒ m₁v₁ = m₂v₂."),
              ],
            },
            {
              key: "ch1", type: "CHALLENGE", difficulty: 4, estimatedMinutes: 40, optional: true, prerequisites: ["n3", "n4"],
              title: "Meydan okuma: asılı kütleyle çekilen eğik düzlemdeki blok",
              learningObjective: "Sürtünmeyi, eğik düzlemi ve bağlı cisimleri tek bir modelde birleştir.",
              tags: ["meydan okuma"],
              questions: [
                num("MASTERY", "30° eğik düzlemdeki 4 kg'lık bir blok (μk = 0,2), tepedeki makaradan geçen iple aşağı inen 3 kg'lık asılı bir kütleye bağlı. İvme? (g = 9,8)", 0.43, "m/s²",
                  ["İki cisim için SCD çiz.", "Eğim boyunca: T − mg sin30 − μk mg cos30 = m a.", "Asılı: Mg − T = M a.", "a = (Mg − mg sin30 − μk mg cos30)/(m + M)."],
                  "a = (29,4 − 19,6 − 6,79)/7 ≈ 0,43 m/s².", 0.05),
              ],
            },
            {
              key: "boss1", type: "BOSS", difficulty: 5, estimatedMinutes: 60, prerequisites: ["e2", "n5", "p2"],
              title: "Final: çember fırlatıcısı",
              learningObjective: "Daha önce görmediğin çok aşamalı bir sistemi analiz etmek için enerji korunumunu, dairesel dinamiği ve momentumu birleştir.",
              masteryCriterion: "İki aşamayı da doğru çöz.",
              requiredCorrect: 2,
              tags: ["final", "olimpiyat"],
              questions: [
                expr("MASTERY", "Bir boncuk h yüksekliğinden durgun hâlden sürtünmesiz kayıyor ve R yarıçaplı düşey bir çemberi tamamlamalı. En küçük h'yi yaz (değişken R).",
                  ["5*R/2", "2.5*R"], ["R"],
                  ["Çemberin tepesinde hangi koşul sağlanmalı?", "En küçük durumda tepede N = 0: v_tepe² = gR.", "Enerji: mgh = mg(2R) + ½ m v_tepe².", "h = 2R + R/2."], "h_min = 5R/2."),
                num("MASTERY", "0,1 kg'lık bir boncuk 0,4 m yarıçaplı bir çemberi tamamlamalı. Alttaki düz yolda u hızıyla kayan 0,5 kg'lık bir blok ona çarpıp yapışarak fırlatıyor. En küçük u (m/s)? (g = 9,8)", 5.31, "m/s",
                  ["Çemberden geriye doğru çalış.", "Birleşik cismin v_alt² = 5gR = 19,6 → v ≈ 4,43 m/s olmalı.", "Çarpışma: 0,5u = 0,6 v.", "u = 1,2 · 4,43."], "v_alt = √(5gR) ≈ 4,43 m/s; u = 0,6v/0,5 ≈ 5,31 m/s."),
                num("TRANSFER", "Hafif bir çubuğa (ip değil) bağlı 0,8 m uzunluğunda bir top, düşey çemberin tepesine ancak ulaşmalı. Alttaki en küçük hız? (g = 9,8)", 5.6, "m/s",
                  ["Çubuk itebilir, yani tepedeki hız sıfır olabilir.", "Enerji: ½mv² = mg(2L).", "v = √(4gL).", "√31,36."], "v = √(4gL) = 5,6 m/s."),
              ],
            },
          ],
        },
      ],
    },
  ],
};
