// Generated by scripts/content-index.mjs — do not edit by hand.
import type { LOText } from "../../schema";
import { EN_MATH, UNITS_MATH } from "./math";
import { EN_MATH_PLUS, UNITS_MATH_PLUS } from "./math_plus";
import { EN_PHYSICS, UNITS_PHYSICS } from "./physics";
import { EN_PHYSICS_PLUS, UNITS_PHYSICS_PLUS } from "./physics_plus";
import { EN_CHEMISTRY, UNITS_CHEMISTRY } from "./chemistry";
import { EN_CHEMISTRY_PLUS, UNITS_CHEMISTRY_PLUS } from "./chemistry_plus";
import { EN_BIOLOGY, UNITS_BIOLOGY } from "./biology";
import { EN_BIOLOGY_PLUS, UNITS_BIOLOGY_PLUS } from "./biology_plus";
import { EN_NEURO, UNITS_NEURO } from "./neuroscience";
import { EN_PROGRAMMING, UNITS_PROGRAMMING } from "./programming";
import { EN_PROGRAMMING_PLUS, UNITS_PROGRAMMING_PLUS } from "./programming_plus";
import { EN_RESEARCH, UNITS_RESEARCH } from "./research";
import { EN_COMPETITION, UNITS_COMPETITION } from "./competition";
import { EN_EARTH, UNITS_EARTH } from "./earth";
import { EN_ENVIRONMENT, UNITS_ENVIRONMENT } from "./environment";
import { EN_PSYCHOLOGY, UNITS_PSYCHOLOGY } from "./psychology";
import { EN_ECONOMICS, UNITS_ECONOMICS } from "./economics";
import { EN_CULTURE, UNITS_CULTURE } from "./culture";
import { EN_CULTURE_PLUS, UNITS_CULTURE_PLUS } from "./culture_plus";
import { EN_WRITING, UNITS_WRITING } from "./writing";
import { EN_ARTS, UNITS_ARTS } from "./arts";
import { EN_MEDIA, UNITS_MEDIA } from "./media";
import { EN_LANGUAGES, UNITS_LANGUAGES } from "./languages";

/** English overlay for every object, keyed by id. */
export const EN_TEXT: Record<string, LOText> = {
  ...EN_MATH,
  ...EN_MATH_PLUS,
  ...EN_PHYSICS,
  ...EN_PHYSICS_PLUS,
  ...EN_CHEMISTRY,
  ...EN_CHEMISTRY_PLUS,
  ...EN_BIOLOGY,
  ...EN_BIOLOGY_PLUS,
  ...EN_NEURO,
  ...EN_PROGRAMMING,
  ...EN_PROGRAMMING_PLUS,
  ...EN_RESEARCH,
  ...EN_COMPETITION,
  ...EN_EARTH,
  ...EN_ENVIRONMENT,
  ...EN_PSYCHOLOGY,
  ...EN_ECONOMICS,
  ...EN_CULTURE,
  ...EN_CULTURE_PLUS,
  ...EN_WRITING,
  ...EN_ARTS,
  ...EN_MEDIA,
  ...EN_LANGUAGES,
};

/** Turkish field/unit names → English. */
export const EN_UNITS: Record<string, string> = {
  ...UNITS_MATH,
  ...UNITS_MATH_PLUS,
  ...UNITS_PHYSICS,
  ...UNITS_PHYSICS_PLUS,
  ...UNITS_CHEMISTRY,
  ...UNITS_CHEMISTRY_PLUS,
  ...UNITS_BIOLOGY,
  ...UNITS_BIOLOGY_PLUS,
  ...UNITS_NEURO,
  ...UNITS_PROGRAMMING,
  ...UNITS_PROGRAMMING_PLUS,
  ...UNITS_RESEARCH,
  ...UNITS_COMPETITION,
  ...UNITS_EARTH,
  ...UNITS_ENVIRONMENT,
  ...UNITS_PSYCHOLOGY,
  ...UNITS_ECONOMICS,
  ...UNITS_CULTURE,
  ...UNITS_CULTURE_PLUS,
  ...UNITS_WRITING,
  ...UNITS_ARTS,
  ...UNITS_MEDIA,
  ...UNITS_LANGUAGES,
};
