// Regenerates src/knowledge/content/index.ts and content/en/index.ts from the
// content files that exist, in a fixed display order. Run after adding content:
//   node scripts/content-index.mjs && node scripts/ledger.mjs
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const ORDER = [
  "math", "math_plus", "physics", "physics_plus", "chemistry", "chemistry_plus", "biology", "biology_plus",
  "neuroscience", "programming", "programming_plus", "research", "competition", "earth", "environment",
  "psychology", "economics", "culture", "culture_plus", "writing", "arts", "media", "languages",
];
const dir = "src/knowledge/content";
const exportsOf = (file, re) => [...readFileSync(file, "utf8").matchAll(re)].map((m) => m[1]);

const base = [], en = [];
for (const name of ORDER) {
  const f = `${dir}/${name}.ts`;
  if (existsSync(f)) base.push({ name, exports: exportsOf(f, /^export const (\w+) = builder\(/gm) });
  const e = `${dir}/en/${name}.ts`;
  if (existsSync(e)) en.push({ name, text: exportsOf(e, /^export const (EN_\w+)/gm), units: exportsOf(e, /^export const (UNITS_\w+)/gm) });
}

writeFileSync(`${dir}/index.ts`, `// Generated by scripts/content-index.mjs — do not edit by hand.
import type { LearningObject } from "../schema";
${base.map((b) => `import { ${b.exports.join(", ")} } from "./${b.name}";`).join("\n")}

/** Canonical (Turkish-authored) content of Lab Curriculum, in display order. */
export const BASE_OBJECTS: LearningObject[] = [
${base.flatMap((b) => b.exports).map((x) => `  ...${x},`).join("\n")}
];
`);

writeFileSync(`${dir}/en/index.ts`, `// Generated by scripts/content-index.mjs — do not edit by hand.
import type { LOText } from "../../schema";
${en.map((e) => `import { ${[...e.text, ...e.units].join(", ")} } from "./${e.name}";`).join("\n")}

/** English overlay for every object, keyed by id. */
export const EN_TEXT: Record<string, LOText> = {
${en.flatMap((e) => e.text).map((x) => `  ...${x},`).join("\n")}
};

/** Turkish field/unit names → English. */
export const EN_UNITS: Record<string, string> = {
${en.flatMap((e) => e.units).map((x) => `  ...${x},`).join("\n")}
};
`);
console.log(`content: ${base.length} files (${base.flatMap((b) => b.exports).length} exports); en: ${en.length} files`);
