// Appends every content id to the permanent id ledger (src/knowledge/ledger.ts).
// The ledger is append-only: existing ids are never removed or reordered.
// Usage: node scripts/ledger.mjs
import { build } from "esbuild";
import { readFileSync, writeFileSync, existsSync, mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { pathToFileURL } from "node:url";

const ledgerPath = "src/knowledge/ledger.ts";
const out = join(mkdtempSync(join(tmpdir(), "ledger-")), "content.mjs");
await build({ entryPoints: ["src/knowledge/content/index.ts"], bundle: true, format: "esm", platform: "node", outfile: out, logLevel: "error" });
const { BASE_OBJECTS } = await import(pathToFileURL(out).href);

const existing = existsSync(ledgerPath) ? [...readFileSync(ledgerPath, "utf8").matchAll(/^  "([^"]+)",$/gm)].map((m) => m[1]) : [];
const seen = new Set(existing);
const added = BASE_OBJECTS.map((o) => o.id).filter((id) => !seen.has(id) && seen.add(id));
const ids = [...existing, ...added];
writeFileSync(ledgerPath, `// Permanent id ledger of Lab Müfredatı. Append-only: generated by scripts/ledger.mjs.
// Never remove or rename an entry; retire objects instead (see registry.ts).
export const ID_LEDGER_V2: readonly string[] = [
${ids.map((id) => `  "${id}",`).join("\n")}
];
`);
console.log(`ledger: ${existing.length} existing, ${added.length} added, ${ids.length} total`);
