import type { CurriculumSpec } from "../../../engines/curriculumSpec";
import { expr, mc, num, open } from "../helpers";

/** Built-in, hand-written pack: olympiad-oriented introductory mechanics. */
export const mechanicsPackEn: CurriculumSpec = {
  title: "Mechanics — Physics Olympiad Track",
  subject: "Physics",
  goal: "Model unseen mechanical systems and solve olympiad-level mechanics problems from first principles.",
  description: "Vectors → kinematics → Newton's laws, then branches into energy and momentum, ending in mixed olympiad challenges.",
  units: [
    {
      title: "Mathematical tools",
      summary: "The language of mechanics: vectors and rates of change.",
      topics: [
        {
          title: "Vectors",
          concepts: [{ key: "vec", title: "Vector components", description: "A vector is described by its components along chosen axes." }],
          milestones: [
            {
              key: "vec1", type: "CONCEPT", difficulty: 1, estimatedMinutes: 8, conceptKeys: ["vec"],
              title: "Resolve a vector into components",
              learningObjective: "Given a vector's magnitude and direction, compute its x and y components and check the signs.",
              masteryCriterion: "Two component calculations correct without the full solution.",
              tags: ["vectors", "trigonometry"],
              questions: [
                num("MASTERY", "A force of 10 N points 30° above the +x axis. What is its x-component?", 8.66, "N",
                  ["Draw the vector and drop a perpendicular to the x-axis.", "The x-component is adjacent to the 30° angle.", "Adjacent side = hypotenuse × cos(angle).", "Fx = 10 · cos 30°."], "Fx = 10 cos 30° = 8.66 N."),
                num("MASTERY", "A velocity of 25 m/s points 53° below the +x axis. What is its y-component (with sign)?", -19.97, "m/s",
                  ["Which direction is 'below' the x-axis?", "The y-component is opposite the angle.", "Use sine for the opposite side, then assign the sign.", "vy = −25 · sin 53°."], "vy = −25 sin 53° ≈ −19.97 m/s."),
                num("RETENTION", "A 12 N force points 60° above the +x axis. What is its y-component?", 10.39, "N",
                  ["Sketch it.", "Opposite side to the angle.", "Use sin.", "12 · sin 60°."], "Fy = 12 sin 60° = 10.39 N."),
                num("TRANSFER", "A box sits on a ramp inclined at 20°. Its weight is 50 N. What is the component of the weight along the ramp?", 17.1, "N",
                  ["Choose axes along and perpendicular to the ramp.", "The angle between weight and the perpendicular axis equals the incline angle.", "The along-ramp component uses sin of the incline angle.", "50 · sin 20°."], "W∥ = 50 sin 20° ≈ 17.1 N."),
              ],
            },
            {
              key: "vec2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 12, prerequisites: ["vec1"],
              title: "Add vectors by components",
              learningObjective: "Add two or more vectors by summing components and recover the magnitude and direction of the result.",
              tags: ["vectors"],
              questions: [
                num("MASTERY", "A = (3, 4) and B = (1, −1). What is |A + B|?", 5, undefined,
                  ["Add like components.", "A + B = (3+1, 4−1).", "Magnitude is √(x² + y²).", "√(4² + 3²)."], "A + B = (4, 3), |A + B| = 5."),
                num("MASTERY", "A hiker walks 4 km east then 3 km north then 1 km west. How far are they from the start (km)?", 4.24, "km",
                  ["Write each leg as a vector.", "East is +x, north is +y.", "Sum: (4 − 1, 3).", "√(3² + 3²)."], "Displacement (3, 3) km → 3√2 ≈ 4.24 km."),
                num("RETENTION", "A = (−2, 5), B = (6, −2). What is |A + B|?", 5, undefined,
                  ["Add components.", "(4, 3).", "Pythagoras.", "5."], "(4, 3) → 5."),
                num("TRANSFER", "Two forces act on a ring: 30 N along +x and 40 N along +y. What single force (magnitude, N) would hold the ring in equilibrium?", 50, "N",
                  ["Equilibrium means the total force is zero.", "Find the resultant of the two forces first.", "The balancing force has the same magnitude as the resultant.", "√(30² + 40²)."], "Resultant 50 N, so a 50 N force in the opposite direction."),
              ],
            },
          ],
        },
        {
          title: "Rates of change",
          milestones: [
            {
              key: "calc1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 12, optional: true, prerequisites: [],
              title: "Differentiate position to get velocity",
              learningObjective: "Obtain v(t) and a(t) from a polynomial x(t) and interpret what each derivative means physically.",
              tags: ["calculus"],
              questions: [
                expr("MASTERY", "x(t) = 3t² + 2t − 5. Write v(t).", ["6*t + 2"], ["t"],
                  ["Velocity is the rate of change of position.", "Differentiate term by term.", "d/dt(tⁿ) = n·tⁿ⁻¹; constants vanish.", "d/dt(3t²) = 6t, d/dt(2t) = 2."], "v(t) = 6t + 2."),
                expr("MASTERY", "x(t) = t³ − 4t. Write a(t).", ["6*t"], ["t"],
                  ["Acceleration is the second derivative.", "First find v(t) = 3t² − 4.", "Differentiate again.", "a(t) = 6t."], "v = 3t² − 4, a = 6t."),
                expr("RETENTION", "x(t) = 5t² − t. Write v(t).", ["10*t - 1"], ["t"],
                  ["Differentiate.", "Power rule.", "10t …", "10t − 1."], "v = 10t − 1."),
                num("TRANSFER", "x(t) = 2t³ − 9t² + 12t (m). At what time t > 1.5 s is the particle momentarily at rest?", 2, "s",
                  ["At rest means v = 0.", "v(t) = 6t² − 18t + 12.", "Divide by 6: t² − 3t + 2 = 0.", "Roots t = 1 and t = 2."], "v = 6(t − 1)(t − 2) → t = 2 s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Kinematics",
      summary: "Describing motion without asking why it happens.",
      topics: [
        {
          title: "Motion graphs and constant acceleration",
          milestones: [
            {
              key: "kin1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 10, prerequisites: ["vec2"],
              title: "Read velocity from a position–time graph",
              learningObjective: "Use the slope of x(t) to determine where velocity is zero, positive or negative.",
              interaction: "GRAPH_INTERPRETATION",
              tags: ["graphs"],
              questions: [
                { kind: "GRAPH_INTERPRETATION", purpose: "MASTERY", prompt: "The graph shows x(t) = t² − 4t (m). At what time is the velocity zero?",
                  graph: { expression: "x^2 - 4*x", xMin: 0, xMax: 5, xLabel: "t (s)", yLabel: "x (m)" }, numeric: { value: 2, tolerance: 0.03, unit: "s" },
                  hints: ["Velocity is the slope of x(t).", "Where is the tangent horizontal?", "That is the turning point of the parabola.", "Vertex of t² − 4t is at t = 2."], solution: "Slope zero at the vertex, t = 2 s." },
                { kind: "GRAPH_INTERPRETATION", purpose: "MASTERY", prompt: "For the same x(t) = t² − 4t, during which interval is the object moving in the −x direction?",
                  graph: { expression: "x^2 - 4*x", xMin: 0, xMax: 5, xLabel: "t (s)", yLabel: "x (m)" },
                  choices: ["0 < t < 2", "2 < t < 4", "0 < t < 4", "t > 4"], correctChoice: 0,
                  hints: ["Negative velocity = negative slope.", "Where is the curve going downhill?", "Before the vertex the curve decreases.", "0 < t < 2."], solution: "Slope negative before the vertex: 0 < t < 2." },
                { kind: "GRAPH_INTERPRETATION", purpose: "RETENTION", prompt: "x(t) = 6t − t² (m). At what time does the object turn around?",
                  graph: { expression: "6*x - x^2", xMin: 0, xMax: 6, xLabel: "t (s)", yLabel: "x (m)" }, numeric: { value: 3, tolerance: 0.03, unit: "s" },
                  hints: ["Turning around means v = 0.", "Horizontal tangent.", "Vertex of the parabola.", "t = 3."], solution: "t = 3 s." },
                mc("TRANSFER", "A ball is thrown straight up. Which statement about its velocity–time graph is true?",
                  ["It is a straight line with negative slope crossing zero at the top", "It is a parabola with its vertex at the top", "It is constant until the top, then jumps to negative", "It is zero everywhere because acceleration is constant"], 0,
                  ["What is the acceleration during flight?", "Constant acceleration ⇒ v(t) is linear.", "The slope is −g.", "v crosses zero at the highest point."], "Constant acceleration −g gives a straight line through v = 0 at the top."),
              ],
            },
            {
              key: "kin2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 15, prerequisites: ["kin1"],
              title: "Solve constant-acceleration problems",
              learningObjective: "Choose the right kinematic relation for the known and unknown quantities and solve it.",
              tags: ["suvat"],
              questions: [
                num("MASTERY", "A car starts from rest with a = 3 m/s². How far does it travel in 4 s?", 24, "m",
                  ["List knowns: v₀, a, t.", "You need displacement without final velocity.", "x = v₀t + ½at².", "½ · 3 · 4²."], "x = ½·3·16 = 24 m."),
                num("MASTERY", "A cyclist moving at 12 m/s brakes uniformly to rest over 18 m. What is the magnitude of the deceleration?", 4, "m/s²",
                  ["Time is not given.", "Use the relation without t.", "v² = v₀² + 2aΔx.", "0 = 144 + 2a·18."], "a = −144/36 = −4 m/s²."),
                num("MASTERY", "A stone is dropped from rest. How fast is it moving after falling 20 m? (g = 9.8 m/s²)", 19.8, "m/s",
                  ["Free fall has a = g.", "No time given.", "v² = 2gh.", "√(2·9.8·20)."], "v = √392 ≈ 19.8 m/s."),
                num("RETENTION", "From rest, a = 2 m/s² for 5 s. Final speed?", 10, "m/s",
                  ["v = v₀ + at.", "v₀ = 0.", "2·5.", "10."], "v = 10 m/s."),
                num("TRANSFER", "A train passes a signal at 20 m/s and decelerates at 0.5 m/s². How long (s) until it has travelled 300 m beyond the signal?", 20, "s",
                  ["Write x(t) and set it to 300.", "300 = 20t − 0.25t².", "Solve the quadratic; pick the first time.", "t² − 80t + 1200 = 0 → t = 20 or 60."], "t = 20 s (the 60 s root is after it would have stopped)."),
              ],
            },
          ],
        },
        {
          title: "Two-dimensional motion",
          milestones: [
            {
              key: "kin3", type: "APPLICATION", difficulty: 3, estimatedMinutes: 25, prerequisites: ["kin2", "vec2"],
              title: "Analyse projectile motion",
              learningObjective: "Treat horizontal and vertical motion independently to find flight time, range and maximum height.",
              interaction: "SIMULATION",
              tags: ["projectile"],
              questions: [
                { kind: "SIMULATION", purpose: "PRACTICE", prompt: "Use the simulator: range R = v²·sin(2θ)/g. Find the launch angle (degrees) that maximises range for any speed.",
                  simulation: { expression: "v^2*sin(2*th*pi/180)/9.8", outputLabel: "Range R (m)", variables: [
                    { name: "v", label: "Speed v (m/s)", min: 5, max: 30, step: 1, initial: 15 },
                    { name: "th", label: "Angle θ (°)", min: 5, max: 85, step: 1, initial: 30 }] },
                  numeric: { value: 45, tolerance: 0.02, unit: "°" },
                  hints: ["Change θ while keeping v fixed.", "Watch when R stops increasing.", "sin(2θ) is largest when 2θ = 90°.", "θ = 45°."], solution: "sin 2θ peaks at 2θ = 90°, so θ = 45°." },
                num("MASTERY", "A ball is launched at 20 m/s, 45° above level ground. What is its range? (g = 9.8)", 40.8, "m",
                  ["Split v into components.", "Time of flight T = 2v sinθ / g.", "R = vₓ · T = v² sin 2θ / g.", "400 · 1 / 9.8."], "R = 400/9.8 ≈ 40.8 m."),
                num("MASTERY", "A ball is thrown horizontally at 8 m/s from a 1.8 m high table. How far from the table does it land? (g = 9.8)", 4.85, "m",
                  ["Vertical motion starts from zero vertical velocity.", "Time from 1.8 = ½gt².", "t ≈ 0.606 s.", "x = 8 · t."], "t = √(3.6/9.8) ≈ 0.606 s, x ≈ 4.85 m."),
                num("RETENTION", "Launched at 15 m/s, 30° above horizontal. Maximum height? (g = 9.8)", 2.87, "m",
                  ["Only vertical motion matters.", "v_y = 15 sin 30° = 7.5.", "h = v_y² / 2g.", "56.25/19.6."], "h ≈ 2.87 m."),
                num("TRANSFER", "A package is released from a plane flying horizontally at 60 m/s at height 500 m. How far ahead of the drop point does it land? (g = 9.8)", 606, "m",
                  ["The package keeps the plane's horizontal speed.", "Fall time from 500 = ½gt².", "t ≈ 10.1 s.", "x = 60 · 10.1."], "t = √(1000/9.8) ≈ 10.10 s → x ≈ 606 m."),
              ],
            },
            {
              key: "kin4", type: "DERIVATION", difficulty: 4, estimatedMinutes: 30, optional: true, prerequisites: ["kin3"],
              title: "Derive the trajectory equation y(x)",
              learningObjective: "Eliminate time from the projectile equations to obtain the path y(x) and recognise it as a parabola.",
              tags: ["derivation", "projectile"],
              questions: [
                expr("MASTERY", "Launch speed v at angle th from the origin, gravity g. Write y as a function of x (use variables x, v, th, g).",
                  ["x*tan(th) - g*x^2/(2*v^2*cos(th)^2)"], ["x", "v", "th", "g"],
                  ["Write x(t) and y(t) separately.", "x = v cos(th) t, so t = x / (v cos th).", "Substitute t into y = v sin(th) t − ½ g t².", "y = x tan th − g x² / (2 v² cos² th)."], "y = x·tan θ − g x² / (2v² cos² θ)."),
                open("DERIVATION", "MASTERY", "Explain, step by step, why the trajectory is a parabola. Name the step that removes time.",
                  ["x is linear in t", "solve x(t) for t", "substitute into y(t)", "y is quadratic in x"],
                  ["Start from the component equations.", "Which equation is easiest to invert?", "x(t) is linear in t.", "After substitution y contains x and x² only."], "x = v cosθ t is linear, so t = x/(v cosθ); substituting into y(t) gives a quadratic in x — a parabola."),
                expr("TRANSFER", "Using y(x), write the range R on level ground in terms of v, th, g (set y = 0, x ≠ 0).",
                  ["v^2*sin(2*th)/g", "2*v^2*sin(th)*cos(th)/g"], ["v", "th", "g"],
                  ["Set y = 0 and divide by x.", "tan th = g R / (2 v² cos² th).", "R = 2 v² sin th cos th / g.", "Use the double-angle identity."], "R = v² sin 2θ / g."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Newton's laws",
      summary: "Why motion changes: forces and their effects.",
      topics: [
        {
          title: "Forces and free-body diagrams",
          concepts: [{ key: "fbd", title: "Free-body diagram", description: "All external forces on one isolated body." }],
          milestones: [
            {
              key: "n1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 15, prerequisites: ["vec2"], conceptKeys: ["fbd"],
              title: "Construct a free-body diagram",
              learningObjective: "Given a physical situation, identify every force acting on one chosen body and draw a correct free-body diagram.",
              interaction: "DIAGRAM",
              masteryCriterion: "Identify the correct set of forces in two unseen situations.",
              tags: ["forces", "fbd"],
              questions: [
                open("DIAGRAM", "PRACTICE", "Draw the free-body diagram of a block sliding down a rough incline. Label every force.",
                  ["weight mg pointing straight down", "normal force perpendicular to the incline", "kinetic friction up the incline (opposing motion)", "no 'force of motion' or extra forces"],
                  ["Isolate the block. What touches it?", "Contact forces: the incline surface only. Field forces: gravity.", "The surface gives two components: perpendicular and parallel.", "Friction opposes the sliding direction."], "Three forces: weight (down), normal (⊥ surface), kinetic friction (up the slope)."),
                mc("MASTERY", "A book rests on a table. Which forces act ON THE BOOK?",
                  ["Weight and normal force from the table", "Weight, normal force, and the book's force on the table", "Only weight", "Weight, normal force and air pressure force upward"], 0,
                  ["Only forces acting on the book count.", "The book pushing on the table acts on the table.", "Two interactions: Earth and table.", "Weight and normal."], "Weight (Earth on book) and normal (table on book)."),
                { kind: "CLASSIFICATION", purpose: "MASTERY", prompt: "A ball swings on a string in a vertical circle. Classify each candidate force on the ball.",
                  classification: { categories: ["Acts on the ball", "Not a real force on the ball"], items: [
                    { text: "Tension from the string", category: "Acts on the ball" },
                    { text: "Gravity", category: "Acts on the ball" },
                    { text: "Centripetal force (as a separate extra force)", category: "Not a real force on the ball" },
                    { text: "Force of the ball's motion", category: "Not a real force on the ball" }] },
                  hints: ["What physically touches the ball?", "Centripetal describes a net-force direction, not a new force.", "Motion does not need a force to sustain it.", "Only tension and gravity."], solution: "Only tension and gravity act; their net provides the centripetal acceleration." },
                mc("RETENTION", "A crate is pulled across a rough floor by a horizontal rope at constant speed. How many forces act on the crate?",
                  ["4", "3", "2", "5"], 0,
                  ["List contact and field forces.", "Rope, floor (two components), Earth.", "Tension, normal, friction, weight.", "4."], "Weight, normal, friction, tension: 4."),
                mc("TRANSFER", "A magnet sticks to a vertical fridge door without sliding. What balances its weight?",
                  ["Static friction from the door", "The magnetic force", "The normal force", "Nothing — it is accelerating slowly"], 0,
                  ["Which direction is the weight?", "Magnetic and normal forces are horizontal.", "A vertical force is required.", "Friction from the surface."], "Magnetic attraction and normal force are horizontal; static friction balances weight."),
              ],
            },
            {
              key: "n2", type: "PRACTICE", difficulty: 2, estimatedMinutes: 15, prerequisites: ["n1"],
              title: "Apply Newton's second law to one body",
              learningObjective: "Write ΣF = ma along chosen axes and solve for an unknown force or acceleration.",
              tags: ["newton2"],
              questions: [
                num("MASTERY", "A 5 kg box is pushed with 20 N; kinetic friction is 5 N. What is its acceleration?", 3, "m/s²",
                  ["Draw the FBD.", "Net horizontal force = push − friction.", "a = F_net / m.", "15 / 5."], "a = (20 − 5)/5 = 3 m/s²."),
                num("MASTERY", "A 70 kg person stands in an elevator accelerating upward at 2 m/s². What does the scale read (N)? (g = 9.8)", 826, "N",
                  ["Forces: normal (scale) up, weight down.", "N − mg = ma.", "N = m(g + a).", "70 · 11.8."], "N = 70 · 11.8 = 826 N."),
                num("RETENTION", "A 2 kg mass has net force 9 N. Acceleration?", 4.5, "m/s²",
                  ["F = ma.", "a = F/m.", "9/2.", "4.5."], "4.5 m/s²."),
                num("TRANSFER", "A frictionless 30° incline. What is the acceleration of a block sliding down it? (g = 9.8)", 4.9, "m/s²",
                  ["Choose axes along the incline.", "Only the along-incline component of weight is unbalanced.", "a = g sin θ.", "9.8 · 0.5."], "a = g sin 30° = 4.9 m/s²."),
              ],
            },
            {
              key: "n3", type: "PRACTICE", difficulty: 3, estimatedMinutes: 20, prerequisites: ["n2"],
              title: "Reason about static and kinetic friction",
              learningObjective: "Decide whether friction is static or kinetic and use μN only when it is valid.",
              tags: ["friction"],
              questions: [
                num("MASTERY", "A block on an incline has μs = 0.5. At what angle (degrees) does it start to slide?", 26.57, "°",
                  ["At the threshold, static friction is at its maximum.", "mg sinθ = μs mg cosθ.", "tan θ = μs.", "arctan(0.5)."], "θ = arctan 0.5 ≈ 26.6°."),
                num("MASTERY", "A 10 kg crate on a floor (μs = 0.4, μk = 0.3) is pushed horizontally with 30 N. What is the friction force (N)? (g = 9.8)", 30, "N",
                  ["Is the push enough to start motion?", "Maximum static friction = μs N = 0.4 · 98 = 39.2 N.", "30 N < 39.2 N, so it does not move.", "Static friction matches the push."], "It stays at rest; static friction = 30 N (not μN)."),
                num("RETENTION", "μk = 0.2, a 5 kg block slides on a level floor. Friction force? (g = 9.8)", 9.8, "N",
                  ["Kinetic friction = μk N.", "N = mg.", "0.2 · 49.", "9.8."], "9.8 N."),
                num("TRANSFER", "A car brakes on a level road with μk = 0.7 between tyres and road (locked wheels). From 20 m/s, what is the stopping distance? (g = 9.8)", 29.15, "m",
                  ["Friction is the only horizontal force.", "a = μk g.", "v² = 2 a d.", "400 / (2 · 6.86)."], "a = 6.86 m/s², d ≈ 29.2 m."),
              ],
            },
            {
              key: "n4", type: "APPLICATION", difficulty: 3, estimatedMinutes: 25, prerequisites: ["n2"],
              title: "Solve connected-body systems",
              learningObjective: "Write Newton's law for each body of a connected system and solve the simultaneous equations.",
              tags: ["systems", "atwood"],
              questions: [
                num("MASTERY", "Atwood machine: 3 kg and 5 kg over a massless frictionless pulley. Acceleration? (g = 9.8)", 2.45, "m/s²",
                  ["Write ΣF = ma for each mass.", "T − m₁g = m₁a and m₂g − T = m₂a.", "Add the equations to eliminate T.", "a = (m₂ − m₁)g/(m₁ + m₂)."], "a = 2·9.8/8 = 2.45 m/s²."),
                expr("MASTERY", "For the Atwood machine with masses m1 and m2, write the string tension T (variables m1, m2, g).",
                  ["2*m1*m2*g/(m1+m2)"], ["m1", "m2", "g"],
                  ["Find a first.", "Then T = m1(g + a).", "Substitute a = (m2 − m1)g/(m1 + m2).", "Simplify the numerator."], "T = 2 m₁ m₂ g / (m₁ + m₂)."),
                num("RETENTION", "Atwood with 2 kg and 6 kg. Acceleration? (g = 9.8)", 4.9, "m/s²",
                  ["Same method.", "a = (m₂ − m₁)g/(m₁ + m₂).", "4·9.8/8.", "4.9."], "4.9 m/s²."),
                num("TRANSFER", "A 4 kg block on a frictionless table is tied over an edge pulley to a hanging 1 kg mass. Acceleration? (g = 9.8)", 1.96, "m/s²",
                  ["Two bodies, one string.", "Hanging: mg − T = ma. Table: T = Ma.", "a = mg/(m + M).", "9.8/5."], "a = 1·9.8/5 = 1.96 m/s²."),
              ],
            },
            {
              key: "n5", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["n2", "kin3"],
              title: "Identify the centripetal force in circular motion",
              learningObjective: "Identify which real forces supply the net inward force and apply ΣF = mv²/r.",
              tags: ["circular"],
              questions: [
                num("MASTERY", "A 1000 kg car rounds a flat curve of radius 50 m at 20 m/s. What friction force is required (N)?", 8000, "N",
                  ["Friction is the only horizontal force.", "It must supply mv²/r.", "1000 · 400 / 50.", "8000 N."], "f = mv²/r = 8000 N."),
                mc("MASTERY", "At the top of a vertical loop, a roller-coaster car moves at just the minimum speed. What provides the centripetal force?",
                  ["Gravity alone", "Normal force alone", "Gravity plus a large normal force", "A separate centripetal force"], 0,
                  ["At minimum speed the track barely touches.", "Then N → 0.", "mg = mv²/r.", "Gravity alone."], "At minimum speed N = 0, so gravity alone supplies mv²/r."),
                num("RETENTION", "A 0.2 kg ball on a 0.5 m string moves in a horizontal circle at 3 m/s. Tension (ignore gravity)?", 3.6, "N",
                  ["T = mv²/r.", "0.2·9/0.5.", "3.6.", "3.6 N."], "3.6 N."),
                num("TRANSFER", "What minimum speed (m/s) is needed at the top of a vertical loop of radius 2.5 m? (g = 9.8)", 4.95, "m/s",
                  ["At the minimum, normal force is zero.", "mg = mv²/r.", "v = √(gr).", "√24.5."], "v = √(9.8·2.5) ≈ 4.95 m/s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Energy",
      summary: "A second route through mechanics: work and conservation.",
      topics: [
        {
          title: "Work and energy",
          milestones: [
            {
              key: "e1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 15, prerequisites: ["n2"],
              title: "Use the work–energy theorem",
              learningObjective: "Relate net work done on a body to its change in kinetic energy.",
              tags: ["energy"],
              questions: [
                num("MASTERY", "A 2 kg cart speeds up from 3 m/s to 5 m/s. How much net work was done on it (J)?", 16, "J",
                  ["W_net = ΔKE.", "KE = ½mv².", "½·2·(25 − 9).", "16 J."], "W = ½·2·(25 − 9) = 16 J."),
                num("MASTERY", "A 0.5 kg puck at 4 m/s slides to rest on rough ice. How much work did friction do (J, with sign)?", -4, "J",
                  ["Friction removes kinetic energy.", "W = KE_f − KE_i.", "0 − ½·0.5·16.", "−4 J."], "W = −4 J."),
                num("RETENTION", "Net work 50 J on a 4 kg body initially at rest. Final speed?", 5, "m/s",
                  ["50 = ½·4·v².", "v² = 25.", "v = 5.", "5 m/s."], "5 m/s."),
                num("TRANSFER", "A 1500 kg car at 25 m/s brakes to rest over 60 m. Average braking force (N)?", 7812.5, "N",
                  ["Work by braking force = ΔKE.", "ΔKE = −½·1500·625.", "F·60 = 468750.", "F = 7812.5 N."], "F = 468750/60 ≈ 7.8 kN."),
              ],
            },
            {
              key: "e2", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["e1"],
              title: "Apply conservation of mechanical energy",
              learningObjective: "Recognise when mechanical energy is conserved and use it to find speeds and heights without forces in detail.",
              tags: ["energy", "conservation"],
              questions: [
                num("MASTERY", "A ball is dropped from 5 m. Speed just before hitting the ground? (g = 9.8)", 9.9, "m/s",
                  ["Potential → kinetic.", "mgh = ½mv².", "v = √(2gh).", "√98."], "v ≈ 9.9 m/s."),
                { kind: "ORDERING", purpose: "MASTERY", prompt: "Put the steps for an energy-conservation solution in order.",
                  orderItems: ["Check that only conservative forces do work", "Choose a zero level for potential energy", "Write total energy at the start", "Write total energy at the end", "Set them equal and solve"],
                  hints: ["What must be true before you can use conservation?", "Then you need a reference.", "Then the two states.", "Finally solve."], solution: "Check validity → choose reference → initial energy → final energy → equate." },
                num("RETENTION", "A pendulum bob is released from 0.45 m above its lowest point. Speed at the bottom? (g = 9.8)", 2.97, "m/s",
                  ["Energy conservation.", "√(2gh).", "√8.82.", "2.97."], "≈ 2.97 m/s."),
                num("TRANSFER", "A skier starts at rest at the top of a frictionless 20 m hill and goes over a 12 m bump. Speed on top of the bump? (g = 9.8)", 12.52, "m/s",
                  ["Only the height difference matters.", "Δh = 8 m.", "v = √(2gΔh).", "√156.8."], "v ≈ 12.5 m/s."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Momentum",
      summary: "A third route: interactions, impulse and collisions.",
      topics: [
        {
          title: "Impulse and collisions",
          milestones: [
            {
              key: "p1", type: "CONCEPT", difficulty: 2, estimatedMinutes: 12, prerequisites: ["n2"],
              title: "Relate impulse to change in momentum",
              learningObjective: "Compute impulse as Δp, paying attention to direction.",
              tags: ["momentum"],
              questions: [
                num("MASTERY", "A 0.5 kg ball hits a wall at 10 m/s and rebounds at 8 m/s. Magnitude of the impulse (N·s)?", 9, "N·s",
                  ["Momentum is a vector.", "Take the rebound direction as positive.", "Δp = m(8 − (−10)).", "0.5 · 18."], "J = 0.5·18 = 9 N·s."),
                num("MASTERY", "A 0.15 kg ball's speed changes from 0 to 40 m/s during a 0.005 s hit. Average force (N)?", 1200, "N",
                  ["F_avg = Δp / Δt.", "Δp = 0.15 · 40 = 6.", "6 / 0.005.", "1200 N."], "F = 1200 N."),
                num("RETENTION", "2 kg, from 3 m/s to 7 m/s in the same direction. Impulse?", 8, "N·s",
                  ["Δp = mΔv.", "2·4.", "8.", "8 N·s."], "8 N·s."),
                mc("TRANSFER", "Why do airbags reduce injury in a crash?",
                  ["They increase the stopping time, so the average force is smaller for the same Δp", "They reduce the change in momentum", "They absorb all of the momentum", "They make the collision elastic"], 0,
                  ["Is Δp changed by the airbag?", "Δp is fixed by the initial and final speeds.", "F = Δp/Δt.", "Longer Δt ⇒ smaller F."], "Same Δp, longer Δt ⇒ smaller average force."),
              ],
            },
            {
              key: "p2", type: "APPLICATION", difficulty: 3, estimatedMinutes: 20, prerequisites: ["p1"],
              title: "Solve one-dimensional collisions",
              learningObjective: "Use momentum conservation and decide whether kinetic energy is conserved.",
              tags: ["collisions"],
              questions: [
                num("MASTERY", "A 2 kg cart at 3 m/s hits a stationary 1 kg cart and they stick. Final speed?", 2, "m/s",
                  ["Momentum is conserved.", "p_before = 6 kg·m/s.", "Total mass after = 3 kg.", "6/3."], "v = 2 m/s."),
                num("MASTERY", "In that collision, how much kinetic energy is lost (J)?", 3, "J",
                  ["Compute KE before and after.", "Before: ½·2·9 = 9 J.", "After: ½·3·4 = 6 J.", "9 − 6."], "3 J lost."),
                num("RETENTION", "4 kg at 5 m/s sticks to 1 kg at rest. Final speed?", 4, "m/s",
                  ["20/5.", "Momentum conservation.", "Total mass 5.", "4."], "4 m/s."),
                num("TRANSFER", "A 60 kg skater at rest throws a 3 kg ball forward at 10 m/s. Skater's recoil speed?", 0.5, "m/s",
                  ["Total momentum stays zero.", "60 v = 3 · 10.", "v = 30/60.", "0.5."], "0.5 m/s backward."),
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Synthesis",
      summary: "Review, challenge and boss problems that combine routes.",
      topics: [
        {
          title: "Review and challenges",
          milestones: [
            {
              key: "rev1", type: "REVIEW", difficulty: 2, estimatedMinutes: 10, prerequisites: ["kin2", "n2"],
              title: "Review: choose the right model",
              learningObjective: "Recognise from the question which principle (kinematics, Newton, energy) is most efficient.",
              tags: ["review"],
              questions: [
                mc("MASTERY", "You know a block's initial speed, the height it climbs on a frictionless ramp, and need its final speed. Most efficient approach?",
                  ["Energy conservation", "Newton's second law along the ramp", "Kinematics with unknown angle", "Momentum conservation"], 0,
                  ["What is unknown? What is not given?", "No time, no angle needed.", "Heights and speeds only.", "Energy."], "Energy conservation only needs heights and speeds."),
                mc("MASTERY", "Two skaters push apart from rest. To find their speed ratio, use…",
                  ["Momentum conservation", "Energy conservation", "Kinematics", "Work–energy theorem"], 0,
                  ["Is there an external horizontal force?", "No ⇒ momentum conserved.", "Initial momentum is zero.", "Momentum."], "Total momentum stays zero ⇒ m₁v₁ = m₂v₂."),
              ],
            },
            {
              key: "ch1", type: "CHALLENGE", difficulty: 4, estimatedMinutes: 40, optional: true, prerequisites: ["n3", "n4"],
              title: "Challenge: block on an incline pulled by a hanging mass",
              learningObjective: "Combine friction, inclines and connected bodies in one model.",
              tags: ["challenge"],
              questions: [
                num("MASTERY", "A 4 kg block on a 30° incline (μk = 0.2) is connected over the top pulley to a hanging 3 kg mass, which descends. Acceleration? (g = 9.8)", 0.43, "m/s²",
                  ["Draw FBDs for both bodies.", "Along the incline: T − mg sin30 − μk mg cos30 = m a.", "Hanging: Mg − T = M a.", "a = (Mg − mg sin30 − μk mg cos30)/(m + M)."],
                  "a = (29.4 − 19.6 − 6.79)/7 ≈ 0.43 m/s².", 0.05),
              ],
            },
            {
              key: "boss1", type: "BOSS", difficulty: 5, estimatedMinutes: 60, prerequisites: ["e2", "n5", "p2"],
              title: "Boss: the loop-the-loop launcher",
              learningObjective: "Combine energy conservation, circular dynamics and momentum to analyse a multi-stage system you have not seen before.",
              masteryCriterion: "Solve both stages correctly.",
              requiredCorrect: 2,
              tags: ["boss", "olympiad"],
              questions: [
                expr("MASTERY", "A bead slides without friction from rest at height h and must complete a vertical loop of radius R. Write the minimum h (variable R).",
                  ["5*R/2", "2.5*R"], ["R"],
                  ["What condition must hold at the top of the loop?", "At minimum, N = 0 at the top: v_top² = gR.", "Energy: mgh = mg(2R) + ½ m v_top².", "h = 2R + R/2."], "h_min = 5R/2."),
                num("MASTERY", "A 0.1 kg bead must complete a 0.4 m-radius loop. It is launched by a 0.5 kg block sliding at speed u that sticks to it on a level track at the bottom. Minimum u (m/s)? (g = 9.8)", 5.31, "m/s",
                  ["Work backwards from the loop.", "Combined body needs v_bottom² = 5gR = 19.6 → v ≈ 4.43 m/s.", "Collision: 0.5u = 0.6 v.", "u = 1.2 · 4.43."], "v_bottom = √(5gR) ≈ 4.43 m/s; u = 0.6v/0.5 ≈ 5.31 m/s."),
                num("TRANSFER", "A ball on a light rod (not a string) of length 0.8 m is to just reach the top of a vertical circle. Minimum speed at the bottom? (g = 9.8)", 5.6, "m/s",
                  ["A rod can push, so the speed at the top may be zero.", "Energy: ½mv² = mg(2L).", "v = √(4gL).", "√31.36."], "v = √(4gL) = 5.6 m/s."),
              ],
            },
          ],
        },
      ],
    },
  ],
};
